version: '3.7'
services:

  traefik:
    image: traefik:v2.5
    ports:
      - 80:80
        #- 443:443
    restart: always
    labels:
      - traefik.enable=true
      - traefik.http.services.traefik-dashboard.loadbalancer.server.port=8080
      - traefik.http.routers.traefik-dashboard-http.entrypoints=http
        #- traefik.http.routers.traefik-dashboard-http.rule=Host(`uportal.in`)
      - traefik.docker.network=traefik-public
        #- traefik.http.routers.traefik-dashboard-https.entrypoints=https
        #- traefik.http.routers.traefik-dashboard-https.rule=Host(`uportal.in`)
        #- traefik.http.middlewares.https-redirect.redirectscheme.scheme=https
        #- traefik.http.middlewares.https-redirect.redirectscheme.permanent=true
        #- traefik.http.routers.traefik-dashboard-http.middlewares=https-redirect
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./sslcerts:/certificates
    command:
      - --providers.docker
      - --providers.docker.exposedbydefault=false
      - --entrypoints.http.address=:80
        #- --entrypoints.https.address=:443
        #- --certificatesresolvers.le.acme.httpchallenge=true
        #- --certificatesresolvers.le.acme.httpchallenge.entrypoint=http
        #- --certificatesresolvers.le.acme.email=sakthiratnam050@gmail.com
        #- --certificatesresolvers.le.acme.storage=/certificates/acme.json
      - --accesslog
      - --log
        #- --api
    networks:
      - traefik-public



networks:
  traefik-public:
    external: true                     
